/* Demonstration models: SI internally unless stated otherwise. No empirical product rankings. */
(function(root){
'use strict';
const g=9.81,air=1.2;
function conductance(c,area=.025){return 1/(1/(8*area)+c.thickness/1000/(c.conductivity*area))+(c.lid===1?.015:.14);}
function thermos(c,minutes=0){const C=c.water/1000*4180+80,G=conductance(c),temperature=c.ambient+(c.initial-c.ambient)*Math.exp(-G*minutes*60/C);return {temperature,minutes,delta:temperature-c.initial,conductance:G,heatLost:C*(c.initial-temperature)};}
// Ice starts at 0 C. While ice remains all heat goes to fusion; after melting water warms.
function cooler(c,minutes=0){const G=conductance(c,.06),mass=c.ice/1000,L=334000,C=mass*4180+100,meltSeconds=mass*L/(G*c.ambient),seconds=minutes*60;return {minutes,remaining:Math.max(0,mass-G*c.ambient*seconds/L)*1000,temperature:seconds<=meltSeconds?0:c.ambient*(1-Math.exp(-G*(seconds-meltSeconds)/C)),conductance:G,meltMinutes:meltSeconds/60};}
// Two equal-capacity thermal nodes represent outer flesh and center; not a cooking/food chemistry model.
function oven(c,minutes=0){const radius=c.diameter/200,density=1050,mass=density*4/3*Math.PI*radius**3,C=mass*3500/2,A=4*Math.PI*radius**2,H=c.convection*A,K=.5*A/radius,dt=.5;let surface=c.initial,core=c.initial;const steps=Math.ceil(minutes*60/dt),h=steps?minutes*60/steps:0;let bandMinutes=0;for(let i=0;i<steps;i++){const transfer=K*(surface-core),external=H*(c.oven-surface),ds=(external-transfer)/C,dc=transfer/C;surface+=ds*h;core+=dc*h;if(core>=60&&core<=80)bandMinutes+=h/60;}return {minutes,core,surface,gap:surface-core,bandMinutes,mass};}
function lighting(c){const h=c.height/100,x=c.offset/100,r=Math.hypot(h,x),cosine=h/r,illuminance=c.intensity*cosine/r**2+c.ambient;return {illuminance,distance:r,inverseSquare:1/r**2,incidence:Math.acos(cosine)*180/Math.PI};}
function circuit(c){const emf=1.5*c.cells,wireR=2*.0175*c.length/c.area,internal=c.cells*c.internal,loadR=c.wiring===0?c.bulbs*c.resistance:c.resistance/c.bulbs,current=emf/(wireR+internal+loadR),loadVoltage=current*loadR,bulbCurrent=c.wiring===0?current:current/c.bulbs,bulbVoltage=bulbCurrent*c.resistance,power=bulbCurrent**2*c.resistance;return {current,bulbVoltage,power,wireR,wirePower:current**2*wireR,internalPower:current**2*internal,loadPower:power*c.bulbs,inputPower:emf*current,emf,loadVoltage};}
function parachute(c){const A=Math.PI*(c.diameter/200)**2,mass=c.mass/1000,k=.5*air*c.drag*A,terminal=Math.sqrt(mass*g/k),height=c.height,time=terminal/g*(g*height/terminal**2+Math.log1p(Math.sqrt(1-Math.exp(-2*g*height/terminal**2))));return {time,terminal,impact:terminal*Math.tanh(g*time/terminal),area:A,mass};}
function parachuteAt(c,time){const r=parachute(c),t=Math.min(r.time,Math.max(0,time)),u=g*t/r.terminal,logCosh=Math.abs(u)+Math.log1p(Math.exp(-2*Math.abs(u)))-Math.LN2;return {...r,elapsed:t,fallen:r.terminal**2/g*logCosh,speed:r.terminal*Math.tanh(u)};}
// Constant-lift point-mass glider, no pitch, stall or fold geometry prediction.
function glider(c){const mass=c.mass/1000,A=c.area/10000,CL=c.lift,CD=c.drag+.12*CL*CL;let x=0,y=c.height,vx=c.speed*Math.cos(c.angle*Math.PI/180),vy=c.speed*Math.sin(c.angle*Math.PI/180),t=0;const path=[{x,y,t}],dt=.002;
 function derivative(s){const [x,y,vx,vy]=s,speed=Math.hypot(vx,vy),q=.5*air*A*speed,drag=q*CD,lift=q*CL;return [vx,vy,(-drag*vx-lift*vy)/mass,(-drag*vy+lift*vx)/mass-g];}
 for(let i=0;i<15000&&y>0;i++){const old={x,y,t},s=[x,y,vx,vy],a=derivative(s),b=derivative(s.map((v,j)=>v+a[j]*dt/2)),d=derivative(s.map((v,j)=>v+b[j]*dt/2)),e=derivative(s.map((v,j)=>v+d[j]*dt));[x,y,vx,vy]=s.map((v,j)=>v+dt*(a[j]+2*b[j]+2*d[j]+e[j])/6);t+=dt;if(y<=0){const f=old.y/(old.y-y);x=old.x+(x-old.x)*f;t=old.t+dt*f;y=0;}if(i%25===0||y===0)path.push({x,y,t});}
 return {range:x,time:t,maxHeight:Math.max(...path.map(p=>p.y)),dragCoefficient:CD,path,landed:y===0};}
function grip(c){const radians=c.angle*Math.PI/180,normal=c.mass/1000*g*Math.cos(radians),down=c.mass/1000*g*Math.sin(radians),limit=c.friction*normal,moving=down>limit+1e-9,kinetic=.75*c.friction,acceleration=moving?g*(Math.sin(radians)-kinetic*Math.cos(radians)):0;return {moving,angle:c.angle,threshold:Math.atan(c.friction)*180/Math.PI,normal,friction:moving?kinetic*normal:down,acceleration,time:moving?Math.sqrt(2*.5/acceleration):null};}
const api={conductance,thermos,cooler,oven,lighting,circuit,parachute,parachuteAt,glider,grip};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.LifeModels=api;
})(typeof window!=='undefined'?window:globalThis);
