'use strict';
(()=>{
const $=id=>document.getElementById(id),P=window.PendulumModel,M=window.StudioModels,LABS=window.STUDIO_LABS,LM=window.LifeModels;
const requested=new URLSearchParams(location.search).get('lab'),lab=Object.hasOwn(LABS,requested)?requested:'rubber',spec=LABS[lab],KEY='sssh-inquiry-studio-v1-'+lab,NS='http://www.w3.org/2000/svg';
const isLife=Object.hasOwn(LM,lab),isFlight=Boolean(spec.flight)||lab==='roller';
let minutes=0,runId=0;
const blank=()=>({version:1,lab,source:'模擬實驗',prediction:'',records:[],notes:{},axes:{x:spec.axes[0][0],y:spec.outputs[0][0]}});
let data=blank(),view='bench',running=false,pending=null,conditions={},q=0,age=0,specimen=1,runTime=0,result=null,fft=[],fitRequested=false,excludeId=null,imported=null,lastFrame=null,lastPaint=0,audio=null;
const voices=new Set();
const finite=(v,a,b)=>typeof v==='number'&&Number.isFinite(v)&&v>=a&&v<=b;
function validate(d){
 if(!d||d.version!==1||d.lab!==lab||d.source!=='模擬實驗'||typeof d.prediction!=='string'||d.prediction.length>5000||!Array.isArray(d.records)||d.records.length>2000||!d.notes||typeof d.notes!=='object'||Array.isArray(d.notes)||!d.axes||!spec.axes.some(a=>a[0]===d.axes.x)||!spec.outputs.some(a=>a[0]===d.axes.y))throw Error('檔案不是這個實驗的完整備份。');
 const ids=new Set();for(const r of d.records){if(!Number.isInteger(r.id)||r.id<1||ids.has(r.id)||!r.conditions||!r.values||!r.meta||typeof r.outcome!=='string'||typeof r.observation!=='string'||typeof r.reason!=='string'||r.observation.length>500||r.reason.length>500||typeof r.excluded!=='boolean'||r.excluded&&!r.reason.trim()||!Number.isFinite(Date.parse(r.at)))throw Error('量測紀錄格式錯誤。');ids.add(r.id);for(const [key,, ,min,max]of spec.controls)if(!finite(r.conditions[key],min,max))throw Error('實驗條件超出範圍。');for(const value of Object.values(r.values))if(value!==null&&!finite(value,-1e8,1e8))throw Error('讀值格式錯誤。');for(const [key]of spec.outputs)if(!Object.hasOwn(r.values,key))throw Error('缺少讀值欄位。');for(const v of Object.values(r.meta))if(typeof v!=='number'||!Number.isFinite(v))throw Error('量測來源資訊錯誤。');}
 for(const key of ['analysisNote','claim','evidence','reasoning','reflection','designPlan'])if(d.notes[key]!==undefined&&(typeof d.notes[key]!=='string'||d.notes[key].length>20000))throw Error('筆記格式錯誤。');return d;
}
try{const old=localStorage.getItem(KEY);if(old)data=validate(JSON.parse(old));}catch(e){$('saveStatus').textContent='舊資料無法讀取，請載入備份';}
runId=Math.max(0,...data.records.map(r=>r.meta.run||0));
specimen=Math.max(0,...data.records.map(r=>r.meta.specimen||0))+1;
function save(){try{localStorage.setItem(KEY,JSON.stringify(data));$('saveStatus').textContent='已儲存於這部裝置';}catch(e){$('saveStatus').textContent='無法本機儲存，請下載備份';}}
function say(t){$('actionStatus').textContent=t;}
function htmlEscape(t){return String(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function params(){return Object.fromEntries(spec.controls.map(([k])=>[k,Number($('param-'+k).value)]));}
function setPanel(open){$('instrumentConsole').hidden=!open;$('controlsToggle').setAttribute('aria-expanded',String(open));document.body.classList.toggle('controls-open',open);}
function sync(){$('timeControls').hidden=!spec.timed;$('timeCursor').disabled=pending!==null;$('advanceTime').disabled=pending!==null||minutes>=spec.maxMinutes;const ready=Boolean(data.prediction);$('predictionGate').hidden=ready;$('run').disabled=!ready||pending!==null||(isFlight&&running);$('secondary').disabled=!ready||pending!==null;$('reset').disabled=!ready||pending!==null;$('setup').disabled=pending!==null||(isFlight&&running);$('cursor').disabled=pending!==null;$('capture').disabled=!running||pending!==null||(isFlight&&runTime<result.time);$('instrumentHud').hidden=view!=='bench'||!running;document.body.classList.toggle('has-timing',running);$('recordCount').textContent=data.records.length;$('monitorCount').textContent=String(data.records.length).padStart(2,'0');$('captureForm').hidden=pending===null;$('sceneState').textContent=pending?'取樣已暫停 · 讀值後保存':running?'實驗進行中':ready?'準備好就操作器材':'先留下你的預測';}
function stopSound(){for(const voice of voices){try{voice.stop();}catch(e){}}voices.clear();}
function stop(message='本次操作已停止；已保存的數據仍在筆記中。'){running=false;pending=null;lastFrame=null;stopSound();sync();say(message);draw();}
function switchView(next){if(!['bench','notebook','analysis','report'].includes(next))return;if(next!==view&&running)stop('離開實驗桌，未保存的取樣已中止。');view=next;document.body.dataset.workspace=next;setPanel(false);$('bench').inert=next!=='bench';for(const el of document.querySelectorAll('.view'))el.hidden=el.id!=='bench'&&el.id!==next;for(const b of document.querySelectorAll('.stations button')){if(b.dataset.view===next)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');}if(next==='notebook')table();if(next==='analysis')analysis();sync();}
for(const b of document.querySelectorAll('[data-view]'))b.addEventListener('click',()=>switchView(b.dataset.view));
for(const [key,item]of Object.entries(LABS)){if($('labSelect').querySelector(`option[value="${key}"]`))continue;const option=document.createElement('option');option.value=key;option.textContent=item.tag.slice(0,2)+' '+item.title;$('labSelect').append(option);}
$('labSelect').value=lab;$('labSelect').addEventListener('change',()=>{stop();location.href=$('labSelect').value==='pendulum'?'../pendulum-workbench/':'?lab='+encodeURIComponent($('labSelect').value);});
$('labHeading').textContent=spec.heading;$('labMission').textContent=spec.mission;$('labTag').textContent=spec.tag;$('panelTag').textContent=spec.tag;$('panelTitle').textContent=spec.title;$('question').textContent=spec.question;$('infoTitle').textContent=spec.title+'｜模型說明';$('modelBoundary').textContent=spec.boundary;$('courseLink').href=spec.link;document.body.dataset.theme=spec.theme||'經典實驗';$('fieldwork').textContent=spec.fieldwork||'用相同條件操作實體器材，記錄模型尚未包含的差異，保留失敗與重複試次。';$('fieldworkReport').textContent=spec.fieldwork||'';document.title=spec.title+'｜探究實驗工作室';
for(const[label,url]of spec.sources){const a=document.createElement('a');a.textContent=label;a.href=url;a.target='_blank';a.rel='noopener';$('sources').append(a);}
function formatControl(control,value){return control[7]?.[value]??(value+' '+control[2]);}
const advancedKeys={thermos:['conductivity'],cooler:['conductivity'],oven:['convection'],lighting:['intensity'],circuit:['resistance','internal'],parachute:['drag'],glider:['lift','drag'],grip:['friction']}[lab]||[];const advanced=document.createElement('details');advanced.className='model-settings';const advancedTitle=document.createElement('summary');advancedTitle.textContent='模型參數（可用實測校準）';advanced.append(advancedTitle);
for(const control of spec.controls){const [key,label,unit,min,max,step,value,choices]=control,wrapper=document.createElement('div'),l=document.createElement('label'),o=document.createElement('output'),input=document.createElement(choices?'select':'input');l.htmlFor='param-'+key;l.className='range-label';l.append(document.createTextNode(label));o.id='value-'+key;o.textContent=formatControl(control,value);l.append(o);input.id='param-'+key;if(choices){for(const [v,t]of Object.entries(choices)){const option=document.createElement('option');option.value=v;option.textContent=t;input.append(option);}input.value=value;}else Object.assign(input,{type:'range',min,max,step,value});input.addEventListener('input',()=>{o.textContent=formatControl(control,Number(input.value));if(!running){const next=params();if(lab==='rubber'&&next.count!==conditions.count){q=0;specimen++;age=0;}conditions=next;result=null;fft=[];minutes=0;draw();}else say('設定已調整。按「'+spec.primary+'」才會套用；現在的讀值仍來自上一組條件。');});wrapper.append(l,input);(advancedKeys.includes(key)?advanced:$('configControls')).append(wrapper);}
if(advancedKeys.length)$('configControls').append(advanced);

conditions=params();$('run').textContent=spec.primary;$('secondary').textContent=spec.secondary;$('reset').textContent=spec.reset;$('soundOption').hidden=lab!=='sound';$('cursor').hidden=lab!=='sound';$('cursorLabel').hidden=lab!=='sound';$('readingLabel').textContent=spec.reading[1]+(spec.reading[2]?'（'+spec.reading[2]+'）':'');Object.assign($('reading'),{min:spec.reading[3],max:spec.reading[4],step:spec.reading[5]});
$('savePrediction').addEventListener('click',()=>{const p=$('prediction').value.trim();if(!p){$('prediction').focus();return;}data.prediction=p;save();sync();say(spec.hint);});
function prepare(){const c=params();if(lab==='rubber'&&c.count!==conditions.count){q=0;specimen++;}conditions=c;age=0;runTime=0;minutes=0;runId++;$('timeCursor').value=0;$('timeValue').textContent='0 min';result=null;pending=null;running=true;lastFrame=performance.now();if(lab==='sound'){result={frequency:M.stringFrequency(c.length,c.mass,c.mu)};fft=M.spectrum(result.frequency);$('cursor').max=spectrumMax();$('cursor').value=Math.min(Number($('cursor').value),spectrumMax());$('cursorValue').textContent=$('cursor').value+' Hz';playSound();}if(lab==='roller')result=M.roller(c);if(lab==='boat')result=M.boat(c);if(isLife)result=LM[lab](c,0);setPanel(false);sync();draw();say(spec.hint);}
if(spec.timed){$('timeCursor').max=spec.maxMinutes;$('advanceTime').textContent='前進 '+spec.timeStep+' 分鐘';}
function seekTime(t){if(!running||pending||!spec.timed)return;minutes=Math.min(spec.maxMinutes,Math.max(0,t));result=LM[lab](conditions,minutes);$('timeCursor').value=minutes;$('timeValue').textContent=minutes+' min';sync();draw();}
$('timeCursor').addEventListener('input',()=>seekTime(Number($('timeCursor').value)));$('advanceTime').addEventListener('click',()=>seekTime(minutes+spec.timeStep));
$('run').addEventListener('click',()=>{if(data.prediction&&!pending)prepare();});
$('secondary').addEventListener('click',()=>{if(lab==='rubber'){$('param-mass').value=0;$('value-mass').textContent='0 g';prepare();}else if(lab==='sound'&&result)playSound();else{stop();setPanel(true);}});
$('reset').addEventListener('click',()=>{stop('已重新準備器材；量測紀錄仍保留。');q=0;age=0;runTime=0;specimen++;for(const[k,,, , , ,v]of spec.controls){$('param-'+k).value=v;$('param-'+k).dispatchEvent(new Event('input'));}conditions=params();draw();});
$('stopRun').addEventListener('click',()=>{stop();setPanel(true);});
async function playSound(){if(lab!=='sound'||!$('soundEnabled').checked||!result)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();await audio.resume();stopSound();const start=audio.currentTime;for(const[h,a]of [[1,.035],[2,.0105],[3,.0042]]){const osc=audio.createOscillator(),gain=audio.createGain();osc.frequency.value=result.frequency*h;gain.gain.setValueAtTime(0,start);gain.gain.linearRampToValueAtTime(a,start+.015);gain.gain.exponentialRampToValueAtTime(.0001,start+1.7);osc.connect(gain);gain.connect(audio.destination);osc.start(start);osc.stop(start+1.8);voices.add(osc);osc.onended=()=>voices.delete(osc);}}catch(e){$('instrumentHint').textContent='此瀏覽器無法播放聲音，仍可操作模擬頻譜。';}}
$('soundEnabled').addEventListener('change',()=>{if(!$('soundEnabled').checked)stopSound();});
$('cursor').addEventListener('input',()=>{$('cursorValue').textContent=$('cursor').value+' Hz';draw();});
function capture(){if(data.records.length>=2000){stop('此實驗已達 2000 筆紀錄，請下載備份。');setPanel(true);return;}if(!running||pending||(isFlight&&runTime<result.time))return;const c={...conditions};pending={conditions:c,at:new Date().toISOString(),meta:{age:Number(age.toFixed(3)),specimen,run:runId},values:{},outcome:'有效讀值'};
 if(isLife){const resultKey=spec.reading[0];pending.meta.modelValue=Number(result[resultKey]??0);if(spec.timed)pending.values.minutes=minutes;const auto=Boolean(spec.flight)||lab==='grip';$('reading').value=auto?(lab==='grip'?(result.moving?'1':'0'):result[resultKey].toFixed(lab==='glider'?1:3)):'';$('reading').readOnly=auto;$('captureContext').textContent=spec.timed?`同一組條件，第 ${minutes} 分鐘。請讀取儀器顯示值；保存後可以繼續快轉並取樣。`:lab==='grip'?'保存這次是否滑動的觀察（0 不滑／1 滑動），與測試角度一起保留。':spec.flight?'已完成這次飛行。保存儀器讀值，再設計下一次比較。':'請讀取儀器顯示值，與這一組條件一起保存。';if(lab==='oven')pending.values.surface=Number(result.surface.toFixed(1));if(lab==='cooler')pending.values.temperature=Number(result.temperature.toFixed(1));if(lab==='lighting')Object.assign(pending.values,{distance:result.distance,inverseSquare:result.inverseSquare});if(lab==='circuit')for(const k of ['bulbVoltage','power','wirePower'])pending.values[k]=result[k];if(lab==='parachute')Object.assign(pending.values,{impact:result.impact,area:result.area});if(lab==='glider')Object.assign(pending.values,{time:result.time,maxHeight:result.maxHeight});if(lab==='grip'){pending.values.normal=result.normal;pending.values.frictionForce=result.friction;pending.outcome=result.moving?'滑動':'不滑動';}}
 if(lab==='rubber'){pending.meta.q=q;pending.meta.position=M.rubberLength(q,c.mass,c.count);pending.values.wait=Number(age.toFixed(2));$('reading').value='';$('reading').readOnly=false;$('captureContext').textContent=`已凍結這一刻：${c.mass} g、${c.count} 條、掛載後 ${age.toFixed(1)} s。請對照尺，讀取下端紅色標記的位置。`;}
 if(lab==='sound'){pending.meta.binWidth=2;pending.meta.sampleRate=8192;pending.meta.sampleCount=4096;$('reading').value=$('cursor').value;$('reading').readOnly=true;$('captureContext').textContent='記錄你選定的頻率游標。若需重新對準，取消取樣後移動游標。';}
 if(lab==='roller'){pending.meta.acceleration=result.acceleration;$('reading').value=result.time.toFixed(3);$('reading').readOnly=true;$('captureContext').textContent='模擬光閘自動讀值至 0.001 s。這是整段通過時間；平均速率由兩閘距離除以時間計算。';}
 if(lab==='boat'){pending.outcome=result.status;pending.values.heel=Math.abs(result.heel);pending.values.freeboard=result.freeboard;pending.meta.capacity=result.capacity;pending.meta.bottomLength=result.length;pending.meta.bottomWidth=result.width;$('reading').readOnly=result.status!=='漂浮';$('reading').value='';$('captureContext').textContent=result.status==='漂浮'?'已凍結這一刻。對照水槽左側刻度，讀取紅色船底中心標記的垂直吃水（水面下為正，上方為負）。':result.reason+' 這次保留為失敗紀錄，不填入尚未成立的平衡讀值。';}
 $('reading').disabled=lab==='boat'&&result.status!=='漂浮';$('observation').value='';sync();setPanel(true);$('captureForm').scrollIntoView({block:'nearest'});if(!$('reading').disabled)$('reading').focus({preventScroll:true});draw();}
$('capture').addEventListener('click',capture);
$('cancelCapture').addEventListener('click',()=>{pending=null;lastFrame=performance.now();sync();setPanel(false);});
$('saveRecord').addEventListener('click',()=>{if(!pending)return;let value=Number($('reading').value);const failed=lab==='boat'&&pending.outcome!=='漂浮';if(!failed&&(!$('reading').value||!finite(value,spec.reading[3],spec.reading[4]))){say('請先填入範圍內的讀值。');$('reading').focus();return;}if(isLife){pending.values[spec.reading[0]]=value;if(lab==='thermos')pending.values.delta=value-pending.conditions.initial;if(lab==='cooler')pending.values.melted=pending.conditions.ice-value;if(lab==='oven')pending.values.gap=pending.values.surface-value;if(lab==='lighting')pending.values.net=value-pending.conditions.ambient;}if(lab==='rubber')Object.assign(pending.values,{length:value,extension:value-12});if(lab==='sound')Object.assign(pending.values,{frequency:value,frequencySquared:value*value,inverseLength:100/pending.conditions.length});if(lab==='roller')Object.assign(pending.values,{time:value,speed:pending.conditions.distance/100/value});if(lab==='boat'){pending.values.draft=failed?null:value;if(failed){pending.values.heel=null;pending.values.freeboard=null;}}
 const id=Math.max(0,...data.records.map(r=>r.id))+1;data.records.push({...pending,id,observation:$('observation').value.trim().slice(0,500),excluded:false,reason:''});pending=null;if(lab!=='rubber'&&!spec.timed){running=false;stopSound();}lastFrame=performance.now();save();sync();setPanel(false);say(`第 ${id} 筆已保存。可重複量測，或調整條件後再操作。`);});
function line(x1,y1,x2,y2,stroke='#76836a',width=1){return `<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${stroke}" stroke-width="${width}"/>`;}
function text(x,y,t,size=12,color='#40583b'){return `<text x="${x}" y="${y}" font-size="${size}" fill="${color}" font-family="system-ui,sans-serif">${htmlEscape(t)}</text>`;}
function ruler(x,y,max,scale,labelEvery=5,min=0){let s=`<rect x="${x}" y="${y+min*scale-16}" width="40" height="${(max-min)*scale+28}" rx="3" fill="url(#rulerFinish)" stroke="#b5a06c"/>`;for(let i=min;i<=max;i++){s+=line(x,y+i*scale,x+(i%labelEvery===0?15:7),y+i*scale,'#71674b',.8);if(i%labelEvery===0)s+=text(x+18,y+i*scale+3,i,9,'#635b3d');}return s;}
function spectrumMax(){return result?Math.min(1600,Math.max(200,Math.ceil(result.frequency*4/200)*200)):1600;}
function draw(){const c=conditions;let s='';if(isLife){const r=result||LM[lab](c,minutes),scene=window.LifeScenes.draw(lab,c,r,{running,elapsed:runTime,minutes});$('apparatus').innerHTML=scene.svg;$('instrumentValue').textContent=scene.value;$('instrumentLabel').textContent=scene.label;$('instrumentHint').textContent=scene.hint;return;}
 if(lab==='rubber'){
 const length=M.rubberLength(q,c.mass,c.count),end=110+length*12,weights=c.mass/25;s=`<ellipse cx="565" cy="550" rx="125" ry="12" fill="#443728" opacity=".2" filter="url(#softShadow)"/><path d="M450 530h228l25 23H426z" fill="url(#basePaint)"/><rect x="648" y="103" width="13" height="430" fill="url(#metal)"/><path d="M650 109H515" stroke="#4b5f50" stroke-width="12" stroke-linecap="round"/>${ruler(420,110,32,12,2)}`;
 for(let i=0;i<c.count;i++){const x=515+i*10;s+=`<path d="M${x} 111C${x-6} 150 ${x-6} ${end-30} ${x} ${end}C${x+6} ${end-30} ${x+6} 150 ${x} 111" fill="none" stroke="#ad7650" stroke-width="3"/>`;}
 s+=line(503,end,546,end,'#a64b35',2)+line(450,end,510,end,'#a64b35',1)+`<path d="M520 ${end}v20h50v6h-72v-6h22" fill="none" stroke="#53624c" stroke-width="3"/>`;
 for(let i=0;i<Math.min(10,weights);i++)s+=`<rect x="500" y="${end+27+i*4}" width="65" height="4" rx="1" fill="url(#metal)" stroke="#52614b" stroke-width=".5"/>`;
 s+=text(501,end+80,c.mass+' g',13)+text(370,505,'讀取紅色下端標記 · 刻度每格 1 cm',10);
 $('instrumentValue').textContent=age.toFixed(1)+' s';$('instrumentLabel').textContent='掛載後有效觀察時間';$('instrumentHint').textContent='讀取下端紅色標記。取樣會暫停畫面，讓你記下讀值。';
 }
 if(lab==='sound'){
 const left=360,right=360+c.length*5,phase=running?Math.sin(runTime*8)*Math.exp(-runTime/2)*10:0;s=`<path d="M337 298h399l22 43H323z" fill="url(#wood)" stroke="#b89c71"/><path d="M323 341h435v15H323z" fill="#795e40"/>${line(left,275,left,335,'#70816c',8)}${line(right,275,right,335,'#70816c',8)}<path d="M${left} 284Q${(left+right)/2} ${284+phase*2} ${right} 284" fill="none" stroke="#bd8a45" stroke-width="2"/><circle cx="${right+12}" cy="285" r="12" fill="url(#metal)"/>${line(right+24,285,right+24,370,'#827453',1.5)}<rect x="${right+4}" y="370" width="40" height="${25+c.mass*.05}" rx="4" fill="url(#metal)"/>${text(left,264,c.length+' cm',12)}${text(right-10,440,c.mass+' g',10)}`;
 s+=`<rect x="343" y="112" width="377" height="123" rx="7" fill="url(#screen)" stroke="#657d63"/>${text(357,129,'SPECTRUM / 模擬頻譜',9,'#bed0b1')}`;
 if(fft.length){const max=Math.max(...fft.map(p=>p.amplitude));let path='';for(const p of fft){if(p.frequency>spectrumMax())break;const x=357+p.frequency/spectrumMax()*347,y=210-p.amplitude/max*67;path+=(path?'L':'M')+x.toFixed(2)+' '+y.toFixed(2);}s+=`<path d="${path}" fill="none" stroke="#d5dda7" stroke-width="1.4"/>`;const cursor=Number($('cursor').value),cx=357+cursor/spectrumMax()*347;s+=line(cx,140,cx,212,'#e9bb73',1)+text(357,148,cursor+' Hz',10,'#f0d0a2');}
 for(let f=0;f<=spectrumMax();f+=spectrumMax()/4)s+=text(354+f/spectrumMax()*347,225,f,8,'#b4c8a5');s+=text(350,495,'弦的振動為慢動作示意；頻譜以模型訊號取樣。',10);
 $('instrumentValue').textContent=$('cursor').value+' Hz';$('instrumentLabel').textContent='頻率游標 · 頻格 2 Hz';$('instrumentHint').textContent='移動游標，對準第一個主要頻峰，再記錄。';
 }
 if(lab==='roller'){
 const model=result||M.roller(c),progress=running?Math.min(1,.5*model.acceleration*runTime**2/(c.distance/100)):0,x1=335,y1=335,x2=746,y2=y1+411*Math.tan(c.slope*Math.PI/180),x=x1+(x2-x1)*progress,y=y1+(y2-y1)*progress-20,angle=running?.5*model.acceleration*Math.min(runTime,model.time)**2/model.axleRadius:0,R=c.radius*5;
 s=`<path d="M${x1} ${y1}L${x2} ${y2}V545H${x1}z" fill="#8b9a80" opacity=".3"/>${line(x1,y1,x2,y2,'#75876b',8)}`;
 for(let i=0;i<=40;i++){const x=x1+(x2-x1)*i/40,y=y1+(y2-y1)*i/40;s+=line(x,y-5,x+2,y+5,'#d6dfc5',2);}
 s+=`<g transform="translate(${x} ${y}) rotate(${angle*180/Math.PI})"><circle r="20" fill="url(#metal)" stroke="#506444" stroke-width="2"/>${line(-R,0,R,0,'#cbb77d',4)}${line(0,-R,0,R,'#cbb77d',4)}<g fill="url(#ball)"><circle cx="${-R}" r="10"/><circle cx="${R}" r="10"/><circle cy="${-R}" r="10"/><circle cy="${R}" r="10"/></g><circle r="5" fill="#36513b"/></g>`;
 for(const[x,y]of [[x1,y1],[x2,y2]])s+=`<path d="M${x-10} ${y+15}v-50h20v50" fill="none" stroke="#384f3b" stroke-width="4"/>${line(x-9,y-11,x+9,y-11,'#b0674f',1)}`;
 s+=`<g transform="translate(523 195)"><circle r="19" fill="url(#metal)" stroke="#6a7b60"/>${line(-R,0,R,0,'#b49e67',3)}${line(0,-R,0,R,'#b49e67',3)}<g fill="url(#ball)"><circle cx="${-R}" r="9"/><circle cx="${R}" r="9"/><circle cy="${-R}" r="9"/><circle cy="${R}" r="9"/></g><circle r="4" fill="#3d543c"/>${line(0,25,R,25,'#657d5b',.8)}${line(0,20,0,30,'#657d5b',.8)}${line(R,20,R,30,'#657d5b',.8)}${text(R/2-13,42,c.radius+' cm',10)}${text(95,-12,'對稱配重',11)}${text(95,10,'總共 '+c.weight+' g',10)}</g>`;
 s+=text(349,475,`配重半徑 ${c.radius} cm · 兩閘距離 ${c.distance} cm`,11)+text(349,496,'理想等效齒軌 · 不含卡齒、撞擊與偏斜',10);
 $('instrumentValue').textContent=(Math.min(runTime,model.time)).toFixed(3)+' s';$('instrumentLabel').textContent='模擬光閘';$('instrumentHint').textContent=runTime>=model.time?'已通過終點。保存這次設計與通過時間。':'光閘計時中，條件暫時鎖定。';
 }
 if(lab==='boat'){
 const r=result||M.boat(c),water=363,scale=10,centerX=545,baseY=running&&r.status==='漂浮'?water+r.draft*scale:running?445:326,w=r.width*scale,h=c.height*scale,phi=running?r.heel:0,depth=70;
 s=`<path d="M318 326l58-35h353l-58 35z" fill="#c9dfd9" opacity=".5"/><path d="M318 326h353v206H318z" fill="#c5dcd4" opacity=".4"/><path d="M671 326l58-35v205l-58 36z" fill="#a3c4b7" opacity=".45"/>`;
 s+=`<g transform="translate(${centerX} ${baseY}) rotate(${-phi})"><path d="M${-w/2} 0h${w}l${depth} -35h${-w}z" fill="#b4b6a6" stroke="#6f7f6c"/><path d="M${-w/2} ${-h}h${w}v${h}h${-w}z" fill="#dce0d0" fill-opacity=".7" stroke="#869781"/><path d="M${w/2} 0l${depth} -35v${-h}l${-depth} 35z" fill="#c4cdb9" stroke="#81937b"/><path d="M${-w/2} ${-h}l${depth} -35h${w}l${-depth} 35" fill="none" stroke="#f3f2df" stroke-width="3"/>`;
 const loadX=c.offset/100*(w/2-5);if(c.load>0)s+=`<rect x="${loadX-16}" y="${-12-Math.min(c.load/35,35)}" width="32" height="${12+Math.min(c.load/35,35)}" rx="2" fill="url(#metal)"/>`;s+=`<circle cx="0" cy="0" r="3" fill="#b64e38"/></g>`;
 s+=`<path d="M318 ${water}h353v169H318z" fill="#7cbab4" opacity=".22"/><path d="M318 ${water}h353l58-35" fill="none" stroke="#519a92" stroke-width="2"/><path d="M318 326v206h353V326M671 532l58-36V291" fill="none" stroke="#718f7a" stroke-width="2"/>`;
 const fold=c.height*4;s+=`<g transform="translate(410 135)"><rect width="120" height="96" fill="#cdd2c3" stroke="#879680"/><rect x="${fold}" y="${fold}" width="${120-2*fold}" height="${96-2*fold}" fill="#eef0e3" stroke="#738b6b" stroke-dasharray="3 3"/>${[[0,0],[120-fold,0],[0,96-fold],[120-fold,96-fold]].map(([x,y])=>`<rect x="${x}" y="${y}" width="${fold}" height="${fold}" fill="#c59b80" opacity=".55"/>`).join('')}${text(0,-12,'30 × 24 cm 鋁箔',11)}${text(140,28,'折邊 '+c.height+' cm',12)}${text(140,51,'虛線＝折線',10)}${text(140,72,'四角切除後折起',10)}</g>`;
 s+=ruler(330,water,10,scale,1,-6)+text(381,300,`底面 ${r.length} × ${r.width} cm`,12)+text(385,507,'紅點＝船底中心；水面為刻度零點',10);
 $('instrumentValue').textContent=running?r.status:'準備下水';$('instrumentLabel').textContent='水槽觀察';$('instrumentHint').textContent=running?r.reason:'先設計船壁與載重，再放入水中。';
 }
 $('apparatus').innerHTML=s;
}
function frame(now){if(running&&!pending&&view==='bench'){if(lastFrame!==null){const dt=(now-lastFrame)/1000;if(dt>.5){stop('觀察中斷超過 0.5 秒，未保存的取樣已停止；請重新操作。');}else{age+=dt;runTime+=dt;if(lab==='rubber')q=M.rubberStep(q,conditions.mass/1000*M.g,conditions.count,dt);}}lastFrame=now;if(now-lastPaint>50){draw();sync();lastPaint=now;}}requestAnimationFrame(frame);}
document.addEventListener('visibilitychange',()=>{if(document.hidden&&running)stop('切換分頁中斷觀察，本次未保存取樣已停止。');});
function table(){const host=$('dataTable');host.replaceChildren();$('initialPrediction').textContent=data.prediction||'尚未留下預測。';$('designSaved').textContent=data.notes.designPlan?'我的比較方法：'+data.notes.designPlan:'';if(!data.records.length){const d=document.createElement('p');d.className='empty-state';d.textContent='回到實驗桌，留下第一筆自己的量測。';host.append(d);return;}const t=document.createElement('table'),head=t.createTHead().insertRow();for(const h of ['編號','操作條件','讀值／結果','觀察與判斷','分析']){const th=document.createElement('th');th.textContent=h;th.scope='col';head.append(th);}const body=t.createTBody();for(const r of data.records){const row=body.insertRow();if(r.excluded)row.className='excluded';const vals=[`#${r.id}`,spec.controls.map(([k,l,u])=>`${l} ${formatControl(spec.controls.find(c=>c[0]===k),r.conditions[k])}`).join('\n')+(spec.timed?`\n第 ${r.values.minutes} min · 第 ${r.meta.run} 組`:'')+(lab==='rubber'?`\n掛載後 ${r.values.wait} s · 橡皮筋組 #${r.meta.specimen}`:''),spec.outputs.map(([k,l])=>`${l}：${r.values[k]===null?'—':Number(r.values[k].toFixed(4))}`).join('\n')+`\n${r.outcome}`,r.observation+(r.excluded?'\n不納入：'+r.reason:'')];for(const value of vals){const cell=row.insertCell();cell.textContent=value||'—';cell.className='note-cell';cell.style.whiteSpace='pre-line';}const b=document.createElement('button');b.textContent=r.excluded?'重新納入':'不納入';b.addEventListener('click',()=>{if(r.excluded){r.excluded=false;save();table();}else{excludeId=r.id;$('excludeReason').value=r.reason;$('excludeDialog').showModal();}});row.insertCell().append(b);}host.append(t);}
$('cancelExclude').addEventListener('click',()=>$('excludeDialog').close());$('excludeForm').addEventListener('submit',e=>{e.preventDefault();const reason=$('excludeReason').value.trim();if(!reason)return;const r=data.records.find(r=>r.id===excludeId);if(r){r.excluded=true;r.reason=reason;save();table();}$('excludeDialog').close();});
function valueFor(r,key){return Object.hasOwn(r.values,key)?r.values[key]:r.conditions[key];}
function points(){return data.records.filter(r=>!r.excluded).map(r=>({x:valueFor(r,data.axes.x),y:valueFor(r,data.axes.y),id:r.id})).filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y));}
function svgEl(name,attrs,t){const el=document.createElementNS(NS,name);for(const[k,v]of Object.entries(attrs||{}))el.setAttribute(k,v);if(t!==undefined)el.textContent=t;return el;}
function graph(svg,pts,fit,residual=false){svg.replaceChildren();const W=residual?360:760,H=residual?240:410,L=residual?63:84,R=24,T=32,B=62;const label=key=>[...spec.axes,...spec.outputs].find(a=>a[0]===key)?.[1]||key;if(!pts.length){svg.append(svgEl('text',{x:W/2,y:H/2,'text-anchor':'middle','font-size':residual?13:18,fill:'#64755e'},residual?'擬合後顯示殘差':'先到實驗桌收集讀值。'));return;}let minX=Math.min(...pts.map(p=>p.x)),maxX=Math.max(...pts.map(p=>p.x)),minY=Math.min(...pts.map(p=>p.y)),maxY=Math.max(...pts.map(p=>p.y));const dx=maxX-minX||Math.max(Math.abs(maxX)*.2,1);minX-=dx*.1;maxX+=dx*.1;if(residual){maxY=Math.max(Math.abs(maxY),Math.abs(minY),.001)*1.2;minY=-maxY;}else{const dy=maxY-minY||Math.max(Math.abs(maxY)*.2,1);minY-=dy*.15;maxY+=dy*.15;}const sx=x=>L+(x-minX)/(maxX-minX)*(W-L-R),sy=y=>H-B-(y-minY)/(maxY-minY)*(H-T-B);for(let i=0;i<=4;i++){const x=minX+(maxX-minX)*i/4,y=minY+(maxY-minY)*i/4;svg.append(svgEl('line',{x1:L,x2:W-R,y1:sy(y),y2:sy(y),stroke:'#dce3d3','stroke-dasharray':'3 5'}),svgEl('text',{x:L-10,y:sy(y)+4,'text-anchor':'end','font-size':11,fill:'#526747'},Number(y.toPrecision(4))),svgEl('text',{x:sx(x),y:H-B+22,'text-anchor':'middle','font-size':11,fill:'#526747'},Number(x.toPrecision(4))));}svg.append(svgEl('path',{d:`M${L} ${T}V${H-B}H${W-R}`,fill:'none',stroke:'#8c9e82'}));if(fit&&!residual){const defs=svgEl('defs'),clip=svgEl('clipPath',{id:'studioPlotClip'});clip.append(svgEl('rect',{x:L,y:T,width:W-L-R,height:H-T-B}));defs.append(clip);svg.append(defs,svgEl('line',{x1:sx(minX),x2:sx(maxX),y1:sy(fit.slope*minX+fit.intercept),y2:sy(fit.slope*maxX+fit.intercept),stroke:'#b18a47','stroke-width':2,'clip-path':'url(#studioPlotClip)'}));}if(residual)svg.append(svgEl('line',{x1:L,x2:W-R,y1:sy(0),y2:sy(0),stroke:'#788e65'}));for(const p of pts){const circle=svgEl('circle',{cx:sx(p.x),cy:sy(p.y),r:residual?4:5,fill:'#365b3d',stroke:'#fffcef','stroke-width':1});circle.append(svgEl('title',{},`#${p.id}：${p.x}, ${p.y}`));svg.append(circle);if(!residual)svg.append(svgEl('text',{x:sx(p.x)+7,y:sy(p.y)-7,'font-size':11,fill:'#4b6841'},'#'+p.id));}svg.append(svgEl('text',{x:(L+W-R)/2,y:H-15,'text-anchor':'middle','font-size':residual?10:13,fill:'#405b37'},label(data.axes.x)),svgEl('text',{x:10,y:17,'font-size':residual?10:13,fill:'#405b37'},residual?'殘差（同縱軸單位）':label(data.axes.y)));}
function analysis(){const pts=points(),fit=fitRequested?P.fit(pts):null;graph($('plot'),pts,fit);graph($('residualPlot'),fit?pts.map((p,i)=>({...p,y:fit.residuals[i]})):[],null,true);const xKey=data.axes.x==='inverseLength'?'length':data.axes.x;const mixed=spec.controls.filter(([key])=>key!==xKey&&new Set(data.records.filter(r=>!r.excluded).map(r=>r.conditions[key])).size>1).map(([,label])=>label);$('analysisNotice').textContent=`${data.records.length} 筆紀錄，${pts.length} 筆有可用於此圖的讀值。`+(mixed.length?'\n其他條件也有變動：'+mixed.join('、')+'。請確認哪些資料適合放在一起比較。':'')+(spec.timed?'\n同一組的不同時間點不是獨立重複；請另外準備多組比較。':'')+(spec.timed&&data.axes.x!=='minutes'&&new Set(data.records.filter(r=>!r.excluded).map(r=>r.values.minutes)).size>1?'\n取樣時間也不相同，請確認是否適合直接比較。':'')+(lab==='rubber'?'\n橡皮筋還受到等待時間與加重／卸載歷程影響，請回看各次紀錄。':'');$('fitResult').textContent=lab==='grip'?'用相鄰的「不滑／滑動」試次夾出開始滑動的角度範圍。二元結果不作直線擬合。':fit?`y = ${fit.slope.toPrecision(5)} x ${fit.intercept<0?'−':'+'} ${Math.abs(fit.intercept).toPrecision(5)}\nR² = ${fit.r2===null?'無法定義（縱軸沒有變化）':fit.r2.toFixed(4)}\n\n斜率單位＝縱軸單位／橫軸單位；截距與縱軸相同。`:fitRequested?'至少需要 3 筆有效讀值，且橫軸至少有兩個不同數值。':'選好座標軸，再決定是否試做直線擬合。';}
for(const[id,items,key]of [['xAxis',spec.axes,'x'],['yAxis',spec.outputs,'y']]){for(const[value,label]of items){const o=document.createElement('option');o.value=value;o.textContent=label;$(id).append(o);}$(id).addEventListener('change',()=>{data.axes[key]=$(id).value;fitRequested=false;save();analysis();});}
if(lab==='grip'){$('fitButton').hidden=true;$('residualPlot').hidden=true;document.querySelector('.fit-panel h3').textContent='把臨界點夾出來';document.querySelector('.fit-panel .small').hidden=true;}
$('fitButton').addEventListener('click',()=>{fitRequested=true;analysis();});for(const el of document.querySelectorAll('[data-note]'))el.addEventListener('input',()=>{data.notes[el.dataset.note]=el.value.slice(0,20000);for(const peer of document.querySelectorAll('[data-note]'))if(peer!==el&&peer.dataset.note===el.dataset.note)peer.value=data.notes[el.dataset.note];save();});
function hydrate(){$('prediction').value=data.prediction;$('initialPrediction').textContent=data.prediction||'尚未留下預測。';$('xAxis').value=data.axes.x;$('yAxis').value=data.axes.y;for(const el of document.querySelectorAll('[data-note]'))el.value=data.notes[el.dataset.note]||'';sync();}
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000);}
function backup(){download(spec.title+'-實驗檔.json',JSON.stringify(data,null,2),'application/json;charset=utf-8');}
$('exportProject').addEventListener('click',backup);$('backupBeforeImport').addEventListener('click',backup);
$('exportCsv').addEventListener('click',()=>{const keys=[...spec.controls.map(c=>c[0]),...new Set([...spec.axes,...spec.outputs].map(a=>a[0]).filter(k=>!spec.controls.some(c=>c[0]===k)))];const rows=[['資料來源','實驗','編號','時間',...keys,'結果','納入分析','不納入理由_最近一次','觀察','量測來源資訊'],...data.records.map(r=>['模擬實驗',spec.title,r.id,r.at,...keys.map(k=>valueFor(r,k)??''),r.outcome,r.excluded?'否':'是',r.reason,r.observation,JSON.stringify(r.meta)])];download(spec.title+'-數據.csv','\uFEFF'+rows.map(r=>r.map(P.csvCell).join(',')).join('\r\n'),'text/csv;charset=utf-8');});
$('exportReport').addEventListener('click',()=>{const fit=fitRequested?P.fit(points()):null;const lines=[`# ${spec.title}｜探究紀錄`,'資料來源：模擬實驗',`匯出時間：${new Date().toISOString()}`,'','## 最初預測',data.prediction||'尚未填寫','','## 原始量測',...data.records.map(r=>`#${r.id} ${r.at}\n模擬時間：${r.values.minutes===undefined?'非時間快轉實驗':r.values.minutes+' min'}\n條件：${spec.controls.map(([k,l,u])=>l+'='+formatControl(spec.controls.find(c=>c[0]===k),r.conditions[k])).join('；')}\n讀值：${spec.outputs.map(([k,l])=>l+'='+(r.values[k]??'無有效讀值')).join('；')}\n結果：${r.outcome}；${r.excluded?'不納入：'+r.reason:'納入分析'}\n觀察：${r.observation||'—'}\n來源資訊：${JSON.stringify(r.meta)}`),'','## 分析設定',`橫軸：${spec.axes.find(a=>a[0]===data.axes.x)[1]}；縱軸：${spec.outputs.find(a=>a[0]===data.axes.y)[1]}`,fit?`直線 y=${fit.slope}x+(${fit.intercept})；R²=${fit.r2??'未定義'}`:'尚未完成直線擬合',...['analysisNote','claim','evidence','reasoning','reflection','designPlan'].flatMap((k,i)=>['',`## ${['分析筆記','我的主張','我的證據','我的解釋','修改或保留預測','我的比較方法'][i]}`,data.notes[k]||'尚未填寫']),'','## 模型邊界',spec.boundary,'','## 實物驗證計畫',spec.fieldwork||'用相同條件實測並比較。'];download(spec.title+'-探究紀錄.md',lines.join('\n'),'text/markdown;charset=utf-8');});
$('importButton').addEventListener('click',()=>$('importFile').click());$('importFile').addEventListener('change',async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{if(f.size>5e6)throw Error('實驗檔超過 5 MB。');imported=validate(JSON.parse(await f.text()));$('infoDialog').close();$('importDialog').showModal();}catch(err){$('saveStatus').textContent='載入失敗：'+err.message;imported=null;}});$('cancelImport').addEventListener('click',()=>{imported=null;$('importDialog').close();});$('confirmImport').addEventListener('click',()=>{if(!imported)return;stop();data=imported;runId=Math.max(0,...data.records.map(r=>r.meta.run||0));specimen=Math.max(0,...data.records.map(r=>r.meta.specimen||0))+1;imported=null;fitRequested=false;save();hydrate();switchView('notebook');$('importDialog').close();});
$('controlsToggle').addEventListener('click',()=>setPanel($('instrumentConsole').hidden));$('closeControls').addEventListener('click',()=>{setPanel(false);$('controlsToggle').focus();});$('infoButton').addEventListener('click',()=>$('infoDialog').showModal());$('closeInfo').addEventListener('click',()=>$('infoDialog').close());
$('fullscreenButton').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch(e){$('saveStatus').textContent='此瀏覽器未提供全螢幕；場景已填滿視窗';}});
document.addEventListener('fullscreenchange',()=>{$('fullscreenButton').textContent=document.fullscreenElement?'退出全螢幕 ⛶':'全螢幕 ⛶';camera();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!document.querySelector('dialog[open]')){if(view!=='bench')switchView('bench');else setPanel(false);}});
function camera(){const zoom=$('zoomRuler').getAttribute('aria-pressed')==='true',ratio=innerWidth/innerHeight,height=zoom?500:760,width=Math.max(zoom?380:520,height*ratio);$('room').setAttribute('viewBox',`${550-width/2} ${zoom?60:-65} ${width} ${width/ratio}`);requestAnimationFrame(()=>{const matrix=$('room').getScreenCTM();if(!matrix)return;for(const[selector,x,y]of [['.notebook-hotspot',305,572],['.computer-hotspot',909,560]]){const p=new DOMPoint(x,y).matrixTransform(matrix),b=document.querySelector(selector);b.style.left=p.x+'px';b.style.top=p.y+'px';b.hidden=zoom||p.x<65||p.x>innerWidth-65||p.y>innerHeight-100;}});}
$('zoomRuler').addEventListener('click',()=>{const zoom=$('zoomRuler').getAttribute('aria-pressed')!=='true';$('zoomRuler').setAttribute('aria-pressed',String(zoom));$('zoomRuler').textContent=zoom?'回到全景':'放大器材';camera();});window.addEventListener('resize',camera);
hydrate();draw();camera();say(spec.hint);requestAnimationFrame(frame);
})();
