const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const m=require('../tools/inquiry-studio/life-models.js');const context={window:{STUDIO_LABS:{}}};vm.runInNewContext(fs.readFileSync(require.resolve('../tools/inquiry-studio/life-labs.js'),'utf8'),context);const specs=context.window.STUDIO_LABS;
const defaults=k=>Object.fromEntries(specs[k].controls.map(c=>[c[0],c[6]]));
const near=(a,b,tol=1e-8)=>assert.ok(Math.abs(a-b)<tol,`${a} != ${b}`);
test('thermos approaches ambient monotonically and adding insulation slows cooling',()=>{const c=defaults('thermos');near(m.thermos(c,0).temperature,c.initial);const a=m.thermos(c,30),b=m.thermos(c,60);assert.ok(c.initial>a.temperature&&a.temperature>b.temperature&&b.temperature>c.ambient);assert.ok(m.thermos({...c,thickness:20},60).temperature>b.temperature);assert.ok(m.thermos({...c,lid:0},60).temperature<b.temperature);assert.ok(m.thermos({...c,water:600},60).temperature>b.temperature);});
test('thermal equilibrium and Newton exponential obey energy and time scaling',()=>{const c=defaults('thermos'),a=m.thermos(c,30),b=m.thermos(c,60),C=c.water/1000*4180+80;near((b.temperature-c.ambient)/(c.initial-c.ambient),((a.temperature-c.ambient)/(c.initial-c.ambient))**2);near(a.heatLost,C*(c.initial-a.temperature));near(m.thermos({...c,initial:c.ambient},60).temperature,c.ambient);});
test('ice latent heat plateau, continuous melt boundary and warm-up',()=>{const c=defaults('cooler'),r=m.cooler(c,0),t=r.meltMinutes;near(m.cooler(c,t/2).remaining,c.ice/2);near(m.cooler(c,t/2).temperature,0);near(m.cooler(c,t).remaining,0);near(m.cooler(c,t).temperature,0);const after=m.cooler(c,t+60);assert.ok(after.temperature>0&&after.temperature<c.ambient);near(m.cooler({...c,ice:c.ice*2},0).meltMinutes,2*t);});
test('oven core lags outer node; larger diameter delays warming; equilibrium preserved',()=>{const c=defaults('oven'),r=m.oven(c,30);assert.ok(r.core>c.initial&&r.core<r.surface&&r.surface<c.oven);assert.ok(m.oven({...c,diameter:9},30).core<r.core);near(m.oven({...c,oven:c.initial},120).core,c.initial);near(m.oven(c,0).core,c.initial);});
test('normal illumination follows inverse square while off-axis includes cosine',()=>{const c={...defaults('lighting'),offset:0,ambient:0};near(m.lighting({...c,height:c.height*2}).illuminance,m.lighting(c).illuminance/4);const r=m.lighting({...c,offset:c.height});near(r.illuminance,m.lighting(c).illuminance/(2*Math.sqrt(2)));near(m.lighting({...c,ambient:100}).illuminance,m.lighting(c).illuminance+100);});
test('circuit conserves power including battery and leads; parallel branch current accounted for',()=>{for(const wiring of [0,1]){const c={...defaults('circuit'),wiring},r=m.circuit(c);near(r.inputPower,r.loadPower+r.wirePower+r.internalPower);near(r.bulbVoltage/c.resistance,wiring?r.current/c.bulbs:r.current);}const c=defaults('circuit');assert.ok(m.circuit({...c,wiring:1}).power>m.circuit({...c,wiring:0}).power);assert.ok(m.circuit({...c,length:5}).current<m.circuit({...c,length:1}).current);});
test('parachute time is longer than free fall and final displacement equals height',()=>{const c=defaults('parachute'),r=m.parachute(c);assert.ok(r.time>Math.sqrt(2*c.height/9.81));near(m.parachuteAt(c,r.time).fallen,c.height);assert.ok(r.impact<r.terminal);assert.ok(m.parachute({...c,diameter:c.diameter*2}).time>r.time);assert.ok(m.parachute({...c,mass:100}).time<r.time);});
test('zero-lift zero-drag glider agrees with independent projectile solution',()=>{const c={...defaults('glider'),lift:0,drag:0},r=m.glider(c),vy=c.speed*Math.sin(c.angle*Math.PI/180),vx=c.speed*Math.cos(c.angle*Math.PI/180),t=(vy+Math.sqrt(vy*vy+2*9.81*c.height))/9.81;near(r.time,t,1e-5);near(r.range,vx*t,1e-4);assert.equal(r.path.at(-1).y,0);assert.equal(r.landed,true);});
test('incline threshold is independent of mass, static friction balances downslope force',()=>{const c=defaults('grip'),theta=Math.atan(c.friction)*180/Math.PI;assert.equal(m.grip({...c,angle:theta-.01}).moving,false);assert.equal(m.grip({...c,angle:theta+.01}).moving,true);near(m.grip({...c,mass:1600}).threshold,m.grip(c).threshold);const r=m.grip(c);near(r.friction,c.mass/1000*9.81*Math.sin(c.angle*Math.PI/180));});
test('all eight models have finite defaults and each control endpoint remains finite',()=>{for(const [key,spec]of Object.entries(specs)){const c=defaults(key);const cases=[c,...spec.controls.flatMap(([k,,,min,max])=>[{...c,[k]:min},{...c,[k]:max}])];for(const input of cases){for(const t of [0,spec.maxMinutes||0]){const r=m[key](input,t);for(const [k,v]of Object.entries(r))if(typeof v==='number')assert.ok(Number.isFinite(v),`${key}.${k} with ${JSON.stringify(input)} @${t}`);if(spec.flight){assert.ok(r.time>0&&r.time<100);if(key==='glider')assert.equal(r.landed,true);}}}}});

test('oven and glider expose conservative operational boundaries without clipping equations',()=>{
 const L=require('../tools/inquiry-studio/life-models.js');
 const c={diameter:6,initial:25,oven:160,convection:15};
 assert.equal(L.oven(c,0).withinRange,true);
 const hot=L.oven(c,120);assert(hot.core>100);assert.equal(hot.withinRange,false);
 const ballistic={mass:10,area:200,lift:0,drag:0,height:1.5,speed:4,angle:10};assert.equal(L.glider(ballistic).withinRange,true);
 const loop={...ballistic,lift:1,speed:15};assert.equal(L.glider(loop).withinRange,false);
});
