'use strict';
(() => {
const $=id=>document.getElementById(id), M=window.PendulumModel, KEY='sssh-pendulum-workbench-v1';
const empty=()=>({version:1,source:'模擬實驗',prediction:'',predictionAt:null,records:[],notes:{},axes:{x:'length',y:'period'}});
let project=empty(), view='bench', running=false, state={angle:Math.PI/12,omega:0}, lastFrame=null, accumulator=0;
let clockStart=null, elapsed=null, runSetup=null, fitRequested=false, pendingExclude=null, pendingImport=null, drag=null;
const bounded=(x,min,max)=>Number.isFinite(x)&&x>=min&&x<=max;
function validate(p){
 if(!p||p.version!==1||p.source!=='模擬實驗'||typeof p.prediction!=='string'||p.prediction.length>5000||!Array.isArray(p.records)||p.records.length>2000||!p.notes||typeof p.notes!=='object'||Array.isArray(p.notes))throw Error('實驗檔格式不符合此工作臺。');
 const ids=new Set();
 for(const r of p.records){
  if(!Number.isInteger(r.id)||r.id<1||ids.has(r.id)||!bounded(r.measuredLength,1,150)||!bounded(r.actualLength,20,120)||!bounded(r.angle,-45,45)||![50,100,200].includes(r.mass)||!bounded(r.elapsed,.1,7200)||!Number.isInteger(r.cycles)||!bounded(r.cycles,1,100)||typeof r.excluded!=='boolean'||typeof r.reason!=='string'||typeof r.observation!=='string'||r.reason.length>300||r.observation.length>300||!Number.isFinite(Date.parse(r.at))||!bounded(r.rulerX,300,610)||!bounded(r.rulerY,65,145)||r.excluded&&!r.reason.trim())throw Error('實驗檔中的量測資料不完整或超出範圍。');
  ids.add(r.id);r.period=r.elapsed/r.cycles;
 }
 for(const k of ['nextInquiry','analysisNote','claim','evidence','reasoning','reflection'])if(p.notes[k]!==undefined&&(typeof p.notes[k]!=='string'||p.notes[k].length>20000))throw Error('筆記格式不正確。');
 if(!p.axes||!['length','angle','mass'].includes(p.axes.x)||!['period','squared'].includes(p.axes.y))throw Error('圖表設定格式不正確。');
 return p;
}
const store=new window.InquiryStorage.RecordStore({key:KEY,storage:{get length(){return localStorage.length;},key:index=>localStorage.key(index),getItem:key=>localStorage.getItem(key),setItem:(key,value)=>localStorage.setItem(key,value)},locks:navigator.locks,validate,empty:empty});
project=store.load();
window.InquiryStorage.mount(store,()=>project,download);
function save(){return store.write(project);}
function say(text){$('actionStatus').textContent=text;}
function config(){return{actualLength:Number($('length').value),angle:Number($('angle').value),mass:Number($('mass').value),rulerX:Number($('rulerX').value),rulerY:Number($('rulerY').value)};}
function drawBob(){const l=Number($('length').value)/100*330,x=520+l*Math.sin(state.angle),y=110+l*Math.cos(state.angle);$('string').setAttribute('x2',x);$('string').setAttribute('y2',y);$('bobHandle').setAttribute('transform',`translate(${x} ${y})`);$('bob').setAttribute('r',Number($('mass').value)===50?14:Number($('mass').value)===100?18:22);}
function drawRuler(){$('ruler').setAttribute('transform',`translate(${$('rulerX').value} ${$('rulerY').value})`);}
function syncControls(){$('monitorCount').textContent=String(project.records.length).padStart(2,'0');const ready=Boolean(project.prediction);document.body.classList.toggle('has-timing',running||elapsed!==null);$('recordFromTimer').hidden=elapsed===null;$('predictionGate').hidden=ready;$('setup').disabled=running;$('release').disabled=!ready||running;$('resetSwing').disabled=!ready;$('timerButton').disabled=!running;$('saveMeasurement').disabled=elapsed===null||clockStart!==null;$('sceneState').textContent=running?'擺動中 · 由你決定量測時機':ready?'器材就緒 · 拖動擺錘設定角度':'等待你的第一個預測';}
function timerText(seconds){$('timer').replaceChildren(document.createTextNode(seconds.toFixed(2).padStart(5,'0')));const s=document.createElement('span');s.textContent=' s';$('timer').append(s);}
function halt(message){running=false;clockStart=null;elapsed=null;lastFrame=null;accumulator=0;state={angle:Number($('angle').value)*Math.PI/180,omega:0};$('timerButton').textContent='開始計時';timerText(0);drawBob();syncControls();if(message)say(message);}
function switchView(next){if(!['bench','notebook','analysis','report'].includes(next))return;if(next!==view&&running)halt('離開實驗桌，本次未保存的計時已中止。已存量測仍保留。');view=next;document.body.dataset.workspace=next;setControls(false);$('bench').inert=next!=='bench';document.querySelectorAll('.view').forEach(el=>{el.hidden=el.id!=='bench'&&el.id!==next;el.classList.toggle('active',el.id===next)});document.querySelectorAll('.stations button').forEach(b=>{if(b.dataset.view===next)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});if(next==='notebook')renderTable();if(next==='analysis')renderAnalysis();}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
$('zoomRuler').addEventListener('click',()=>{const zoom=$('zoomRuler').getAttribute('aria-pressed')!=='true';$('zoomRuler').setAttribute('aria-pressed',String(zoom));$('zoomRuler').textContent=zoom?'回到全景':'放大讀尺';updateCamera(zoom);document.querySelector('.scene-wrap').classList.toggle('zoomed',zoom);});
$('savePrediction').addEventListener('click',async()=>{const p=$('prediction').value.trim();if(!p){$('prediction').focus();say('先寫下你的預測與理由。');return;}project.prediction=p.slice(0,5000);project.predictionAt=new Date().toISOString();const saved=await save();$('initialPrediction').textContent=project.prediction;syncControls();say(saved?'預測已保存。調整條件後釋放擺錘，用尺讀取擺長。':'預測只在本頁，請先處理儲存提示。');});
['length','angle','mass'].forEach(id=>$(id).addEventListener('input',()=>{if(running)return;elapsed=null;timerText(0);$('lengthOut').textContent=$('length').value+' cm';$('angleOut').textContent=$('angle').value+'°';state={angle:Number($('angle').value)*Math.PI/180,omega:0};if(id==='length')$('measuredLength').value='';drawBob();syncControls();}));
['rulerX','rulerY'].forEach(id=>$(id).addEventListener('input',drawRuler));
$('release').addEventListener('click',()=>{if(!project.prediction||running)return;if(Math.abs(Number($('angle').value))<3){say('請把擺錘拉開至少 3°，再釋放。');return;}runSetup=config();state={angle:runSetup.angle*Math.PI/180,omega:0};running=true;lastFrame=performance.now();accumulator=0;clockStart=null;elapsed=null;timerText(0);syncControls();setControls(false);say('擺錘已釋放。選定觀察位置，按下碼錶開始計時。');});
$('resetSwing').addEventListener('click',()=>halt('已重新架設。原始量測保留在筆記中，可調整條件再測一次。'));
$('timerButton').addEventListener('click',()=>{if(!running)return;if(clockStart===null){clockStart=performance.now();elapsed=null;$('timerButton').textContent='停止計時';say('正在計時。自己數完整來回，再按停止。');}else{elapsed=Math.round((performance.now()-clockStart)/10)/100;clockStart=null;if(elapsed<.1){elapsed=null;say('計時太短，請重新開始。');}else say('填入你讀到的擺長與實際數到的完整來回次數，再保存。');$('timerButton').textContent='重新計時';timerText(elapsed||0);}syncControls();});
$('measurementForm').addEventListener('submit',async e=>{e.preventDefault();if(project.records.length>=2000){say('此實驗已達 2000 筆紀錄，請下載實驗檔備份。');return;}if(elapsed===null||clockStart!==null||!runSetup)return;const length=Number($('measuredLength').value),cycles=Number($('cycles').value);if(!bounded(length,1,150)||!Number.isInteger(cycles)||!bounded(cycles,1,100)||elapsed>7200){say('請檢查擺長、完整來回次數與計時。');return;}const id=Math.max(0,...project.records.map(r=>r.id))+1;project.records.push({...runSetup,id,at:new Date().toISOString(),measuredLength:length,cycles,elapsed,period:elapsed/cycles,observation:$('observation').value.trim().slice(0,300),excluded:false,reason:''});elapsed=null;const saved=await save();$('recordFromTimer').hidden=true;$('saveMeasurement').disabled=true;$('recordCount').textContent=project.records.length;$('monitorCount').textContent=String(project.records.length).padStart(2,'0');$('observation').value='';say(saved?`第 ${id} 筆已保存。可用同一條件再計時，或重新架設後補測。`:'新紀錄只在本頁，尚未存入裝置；請下載本頁副本。');});
function frame(now){if(running){const dt=(now-lastFrame)/1000;lastFrame=now;if(dt>.5){halt('畫面暫停超過 0.5 秒，這次計時已中止。請重新釋放後量測。');}else{accumulator+=Math.max(0,dt);while(accumulator>=1/240){state=M.step(state,runSetup.actualLength/100,1/240);accumulator-=1/240;}drawBob();if(clockStart!==null)timerText((now-clockStart)/1000);}}requestAnimationFrame(frame);}
document.addEventListener('visibilitychange',()=>{if(document.hidden&&running)halt('切換分頁使觀察中斷，本次計時已中止。請重新量測。');});
function svgPoint(e){return new DOMPoint(e.clientX,e.clientY).matrixTransform($('room').getScreenCTM().inverse());}
for(const kind of ['bobHandle','ruler']){$(kind).addEventListener('pointerdown',e=>{if(running||e.button!==0)return;const p=svgPoint(e);drag={kind,id:e.pointerId,x:p.x,y:p.y,rx:Number($('rulerX').value),ry:Number($('rulerY').value)};$(kind).setPointerCapture(e.pointerId);e.preventDefault();});$(kind).addEventListener('pointermove',e=>{if(!drag||drag.kind!==kind||drag.id!==e.pointerId)return;const p=svgPoint(e);if(kind==='bobHandle'){const a=Math.round(Math.max(-45,Math.min(45,Math.atan2(p.x-520,p.y-110)*180/Math.PI)));$('angle').value=a;$('angle').dispatchEvent(new Event('input'));}else{$('rulerX').value=Math.max(300,Math.min(610,drag.rx+p.x-drag.x));$('rulerY').value=Math.max(65,Math.min(145,drag.ry+p.y-drag.y));drawRuler();}});for(const ev of ['pointerup','pointercancel','lostpointercapture'])$(kind).addEventListener(ev,()=>{drag=null;});}
const NS='http://www.w3.org/2000/svg';function svgEl(name,attrs,text){const el=document.createElementNS(NS,name);for(const[k,v]of Object.entries(attrs||{}))el.setAttribute(k,v);if(text!==undefined)el.textContent=text;return el;}
for(let i=0;i<=120;i++){const y=i*3.3;$('rulerTicks').append(svgEl('line',{x1:0,y1:y,x2:i%10===0?17:i%5===0?12:7,y2:y,stroke:'#6d6546','stroke-width':i%10===0?1.1:.6}));if(i%10===0)$('rulerTicks').append(svgEl('text',{x:20,y:y+4,'font-size':10,fill:'#4d563c'},i));}
function renderTable(){const host=$('dataTable');host.replaceChildren();if(!project.records.length){const d=document.createElement('div');d.className='empty-state';d.textContent='筆記還是空白的。回實驗桌，親手完成第一筆量測。';host.append(d);return;}const table=document.createElement('table'),head=table.createTHead(),row=head.insertRow();for(const h of ['編號','量得 L','條件：設定 L／角度／質量','總時間／次數','週期 T','觀察與判斷','分析']){const th=document.createElement('th');th.scope='col';th.textContent=h;row.append(th);}const body=table.createTBody();for(const r of project.records){const tr=body.insertRow();if(r.excluded)tr.className='excluded';const vals=[`#${r.id}`,`${r.measuredLength.toFixed(1)} cm`,`${r.actualLength} cm ／ ${r.angle}° ／ ${r.mass} g`,`${r.elapsed.toFixed(2)} s ／ ${r.cycles}`,`${r.period.toFixed(3)} s`,r.observation+(r.excluded?`\n不納入：${r.reason}`:'')];vals.forEach((v,i)=>{const cell=tr.insertCell();cell.textContent=v||'—';if(i===5){cell.className='note-cell';cell.style.whiteSpace='pre-wrap';}});const cell=tr.insertCell(),b=document.createElement('button');b.textContent=r.excluded?'重新納入':'不納入';b.addEventListener('click',()=>{if(r.excluded){r.excluded=false;save();renderTable();}else{pendingExclude=r.id;$('excludeReason').value=r.reason;$('excludeDialog').showModal();$('excludeReason').focus();}});cell.append(b);}host.append(table);}
$('cancelExclude').addEventListener('click',()=>$('excludeDialog').close());$('excludeForm').addEventListener('submit',e=>{e.preventDefault();const reason=$('excludeReason').value.trim();if(!reason)return;const r=project.records.find(r=>r.id===pendingExclude);if(r){r.excluded=true;r.reason=reason;save();renderTable();}$('excludeDialog').close();});
const labels={length:'量得擺長 L（m）',angle:'釋放角度的大小（°）',mass:'擺錘質量（g）',period:'週期 T（s）',squared:'週期平方 T²（s²）'};
function points(){return project.records.filter(r=>!r.excluded).map(r=>({x:project.axes.x==='length'?r.measuredLength/100:project.axes.x==='angle'?Math.abs(r.angle):r.mass,y:project.axes.y==='period'?r.period:r.period**2,id:r.id}));}
function plot(svg,pts,fit,residual=false){svg.replaceChildren();const W=residual?360:760,H=residual?240:410,L=residual?60:80,R=25,T=30,B=65;if(!pts.length){svg.append(svgEl('text',{x:W/2,y:H/2,'text-anchor':'middle',fill:'#64755e','font-size':residual?13:19},residual?'擬合後顯示殘差':'還沒有量測。回實驗桌收集你的第一筆數據。'));return;}
 const xs=pts.map(p=>p.x),ys=pts.map(p=>p.y);let minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);const dx=(maxX-minX)||Math.max(Math.abs(maxX)*.2,.1);minX-=dx*.12;maxX+=dx*.12;if(residual){const span=Math.max(Math.abs(minY),Math.abs(maxY),.001)*1.3;minY=-span;maxY=span;}else{const dy=(maxY-minY)||Math.max(maxY*.2,.1);minY=Math.max(0,minY-dy*.18);maxY+=dy*.18;}
 const sx=x=>L+(x-minX)/(maxX-minX)*(W-L-R),sy=y=>H-B-(y-minY)/(maxY-minY)*(H-T-B);
 for(let i=0;i<=4;i++){const y=minY+(maxY-minY)*i/4,x=minX+(maxX-minX)*i/4;svg.append(svgEl('line',{x1:L,y1:sy(y),x2:W-R,y2:sy(y),stroke:'#dfe5d8','stroke-dasharray':'3 5'}),svgEl('text',{x:L-12,y:sy(y)+4,'text-anchor':'end','font-size':residual?10:12,fill:'#5b6b54'},y.toFixed(residual?4:2)),svgEl('text',{x:sx(x),y:H-B+23,'text-anchor':'middle','font-size':residual?10:12,fill:'#5b6b54'},x.toFixed(project.axes.x==='length'?2:0)));}
 svg.append(svgEl('path',{d:`M${L} ${T}V${H-B}H${W-R}`,fill:'none',stroke:'#8c9e82'}));
 if(residual)svg.append(svgEl('line',{x1:L,y1:sy(0),x2:W-R,y2:sy(0),stroke:'#627b53','stroke-width':1.5}));
 if(fit&&!residual){const id='plotClip';const defs=svgEl('defs');const clip=svgEl('clipPath',{id});clip.append(svgEl('rect',{x:L,y:T,width:W-L-R,height:H-T-B}));defs.append(clip);svg.append(defs,svgEl('line',{x1:sx(minX),y1:sy(fit.slope*minX+fit.intercept),x2:sx(maxX),y2:sy(fit.slope*maxX+fit.intercept),stroke:'#ab8441','stroke-width':2,'clip-path':`url(#${id})`}));}
 for(const p of pts){const c=svgEl('circle',{cx:sx(p.x),cy:sy(p.y),r:residual?4:5,fill:'#315d45',stroke:'#fffefa','stroke-width':1.5});c.append(svgEl('title',{},`#${p.id}：${p.x.toFixed(3)}, ${p.y.toFixed(4)}`));svg.append(c);if(!residual)svg.append(svgEl('text',{x:sx(p.x)+8,y:sy(p.y)-8,'font-size':11,fill:'#476b46'},`#${p.id}`));}
 svg.append(svgEl('text',{x:(L+W-R)/2,y:H-14,'text-anchor':'middle','font-size':residual?11:14,fill:'#425b3d'},labels[project.axes.x]),svgEl('text',{x:14,y:17,'font-size':residual?11:14,fill:'#425b3d'},residual?`殘差（${project.axes.y==='period'?'s':'s²'}）`:labels[project.axes.y]));
}
function renderAnalysis(){const pts=points(),r=project.records.filter(r=>!r.excluded);let warning='';const controls=project.axes.x==='length'?['angle','mass']:project.axes.x==='angle'?['actualLength','mass']:['actualLength','angle'];const varied=controls.filter(k=>new Set(r.map(x=>k==='angle'?Math.abs(x[k]):x[k])).size>1);if(varied.length)warning='這些量測同時改變了其他條件。請回筆記檢查哪些資料適合一起分析；擬合本身不能隔離變因。';$('analysisNotice').textContent=`納入 ${pts.length} 筆模擬量測；未納入 ${project.records.length-pts.length} 筆。${warning||'請先確認各筆量測的控制條件是否一致。'}`;const fit=fitRequested?M.fit(pts):null;plot($('plot'),pts,fit);plot($('residualPlot'),fit?pts.map((p,i)=>({...p,y:fit.residuals[i]})):[],null,true);$('fitResult').textContent=fit?`y = ${fit.slope.toFixed(4)} x ${fit.intercept<0?'−':'+'} ${Math.abs(fit.intercept).toFixed(4)}\nR² = ${fit.r2===null?'無法定義（y 沒有變化）':fit.r2.toFixed(4)}\n\n斜率單位：${project.axes.y==='period'?'s':'s²'} / ${project.axes.x==='length'?'m':project.axes.x==='angle'?'°':'g'}\n截距單位：${project.axes.y==='period'?'s':'s²'}\n\n請同時查看散佈圖與殘差；R² 高不代表已證明因果。`:fitRequested?'至少需要 3 筆納入的量測，而且橫軸必須有不同數值，才能在此試做直線擬合。':'先收集數據，選好橫軸與縱軸，再試做直線擬合。';}
$('fitButton').addEventListener('click',()=>{fitRequested=true;renderAnalysis();});for(const id of ['xAxis','yAxis'])$(id).addEventListener('change',()=>{project.axes={x:$('xAxis').value,y:$('yAxis').value};fitRequested=false;save();renderAnalysis();});
document.querySelectorAll('[data-note]').forEach(el=>el.addEventListener('input',()=>{project.notes[el.dataset.note]=el.value.slice(0,20000);save();}));
function hydrate(){$('initialPrediction').textContent=project.prediction||'尚未留下預測。';$('prediction').value=project.prediction;$('recordCount').textContent=project.records.length;$('xAxis').value=project.axes.x;$('yAxis').value=project.axes.y;document.querySelectorAll('[data-note]').forEach(el=>{el.value=project.notes[el.dataset.note]||''});syncControls();renderTable();renderAnalysis();}
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000);}
function exportProject(){if(store.blocked==='corrupt'){download('原始紀錄-請保留.json',store.raw,'application/json');return;}download('單擺工作臺-實驗檔.json',JSON.stringify(project,null,2),'application/json;charset=utf-8');}
$('exportProject').addEventListener('click',exportProject);$('backupBeforeImport').addEventListener('click',exportProject);
$('exportCsv').addEventListener('click',()=>{const rows=[['資料來源','編號','時間','量得擺長_cm','設定擺長_cm','釋放角度_deg','質量_g','計時_s','完整週期數','週期_s','尺水平位置_svg','尺零點位置_svg','納入分析','不納入理由_最近一次','觀察'],...project.records.map(r=>['模擬實驗',r.id,r.at,r.measuredLength,r.actualLength,r.angle,r.mass,r.elapsed,r.cycles,r.period,r.rulerX,r.rulerY,r.excluded?'否':'是',r.reason,r.observation])];download('單擺工作臺-量測數據.csv','\uFEFF'+rows.map(r=>r.map(v=>M.csvCell(typeof v==='number'?Number(v.toPrecision(10)):v)).join(',')).join('\r\n'),'text/csv;charset=utf-8');});
$('exportReport').addEventListener('click',()=>{const fit=M.fit(points());const lines=['# 單擺工作臺｜探究紀錄','資料來源：模擬實驗',`匯出時間：${new Date().toISOString()}`,'','## 最初預測',project.prediction||'尚未填寫','','## 後續研究問題、預測與比較方法',project.notes.nextInquiry||'尚未填寫','','## 原始量測',...project.records.map(r=>`#${r.id}｜量得 L=${r.measuredLength} cm；設定 L=${r.actualLength} cm；角度=${r.angle}°；質量=${r.mass} g；${r.elapsed.toFixed(2)} s / ${r.cycles} 次 = ${r.period.toFixed(4)} s\n${r.excluded?'不納入：'+r.reason:'納入分析'}；觀察：${r.observation||'—'}${!r.excluded&&r.reason?'；曾不納入的理由：'+r.reason:''}`),'','## 分析',`橫軸：${labels[project.axes.x]}；縱軸：${labels[project.axes.y]}`,fitRequested&&fit?`直線：y=${fit.slope}x+(${fit.intercept})；R²=${fit.r2??'無法定義'}`:'尚未完成直線擬合',project.notes.analysisNote||'尚未填寫',...['claim','evidence','reasoning','reflection'].flatMap((k,i)=>['',`## ${['我的主張','支持主張的證據','我如何解釋證據','回看預測與下一步'][i]}`,project.notes[k]||'尚未填寫']),'','模型邊界：無摩擦的質點單擺，θ″=−(9.81/L)sinθ；量測來自手動計時與讀尺。模擬數據無法獨立驗證產生數據的模型。'];download('單擺工作臺-探究紀錄.md',lines.join('\n'),'text/markdown;charset=utf-8');});
$('importButton').addEventListener('click',()=>$('importFile').click());$('importFile').addEventListener('change',async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{if(f.size>5e6)throw Error('檔案過大，請使用此工作臺匯出的 JSON 實驗檔。');pendingImport=validate(JSON.parse(await f.text()));$('importDialog').showModal();}catch(err){$('importError').textContent='載入失敗：'+err.message;pendingImport=null;}});$('cancelImport').addEventListener('click',()=>{$('importDialog').close();pendingImport=null;});$('confirmImport').addEventListener('click',async()=>{if(!pendingImport)return;if(!await store.write(pendingImport,{recover:store.blocked==='corrupt'})){$('importDialog').close();$('infoDialog').close();return;}halt();project=pendingImport;pendingImport=null;fitRequested=false;hydrate();$('infoDialog').close();switchView('notebook');$('importDialog').close();});

function setControls(open){
 $('instrumentConsole').hidden=!open;
 $('controlsToggle').setAttribute('aria-expanded',String(open));
 document.body.classList.toggle('controls-open',open);
}
function updateCamera(zoom=$('zoomRuler').getAttribute('aria-pressed')==='true'){
 const ratio=innerWidth/innerHeight;
 const height=zoom?500:760;
 const width=Math.max(zoom?340:500,height*ratio);
 const actualHeight=width/ratio;
 const cx=zoom?490:550;
 $('room').setAttribute('viewBox',`${cx-width/2} ${zoom?50:-65} ${width} ${actualHeight}`);
 // Place scene buttons on their actual objects at every viewport aspect ratio.
 requestAnimationFrame(()=>{
  const matrix=$('room').getScreenCTM();if(!matrix)return;
  for(const [selector,x,y] of [['.notebook-hotspot',305,572],['.computer-hotspot',909,560]]){
   const point=new DOMPoint(x,y).matrixTransform(matrix),button=document.querySelector(selector);
   button.style.left=point.x+'px';button.style.top=point.y+'px';
   button.hidden=point.x<65||point.x>innerWidth-65||point.y>innerHeight-100||zoom;
  }
 });
}
$('controlsToggle').addEventListener('click',()=>setControls($('instrumentConsole').hidden));
$('closeControls').addEventListener('click',()=>{setControls(false);$('controlsToggle').focus();});
$('recordFromTimer').addEventListener('click',()=>{setControls(true);$('measurementForm').scrollIntoView({block:'nearest'});$('measuredLength').focus({preventScroll:true});});
$('infoButton').addEventListener('click',()=>$('infoDialog').showModal());
$('closeInfo').addEventListener('click',()=>$('infoDialog').close());
$('fullscreenButton').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else $('saveStatus').textContent='目前瀏覽器未提供全螢幕功能；場景已填滿視窗';}catch(e){$('saveStatus').textContent='目前視窗無法切換全螢幕；場景已填滿視窗';}});
document.addEventListener('fullscreenchange',()=>{$('fullscreenButton').textContent=document.fullscreenElement?'退出全螢幕 ⛶':'全螢幕 ⛶';updateCamera();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!document.querySelector('dialog[open]')){if(view!=='bench')switchView('bench');else setControls(false);}});
window.addEventListener('resize',()=>updateCamera());
// The stopwatch floats over the scene, independent of the collapsible setup panel.
$('bench').append(document.querySelector('.stopwatch'));
updateCamera();

hydrate();drawRuler();drawBob();if(project.prediction)say('先前紀錄已載入。可開始新的量測，或到筆記接續分析。');requestAnimationFrame(frame);
})();
